# Generated by Django 4.2.2 on 2025-04-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_link_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='status',
            field=models.CharField(choices=[('analyzing', 'Аналізується'), ('done', 'Завершено'), ('error', 'Помилка')], default='done', max_length=20),
        ),
        migrations.AddField(
            model_name='link',
            name='status',
            field=models.CharField(choices=[('analyzing', 'Аналізується'), ('done', 'Завершено'), ('error', 'Помилка')], default='done', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(choices=[('analyzing', 'Аналізується'), ('done', 'Завершено'), ('error', 'Помилка')], default='done', max_length=20),
        ),
    ]
