# Generated by Django 4.2.2 on 2025-04-27 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_attachment_status_link_status_uploadedfile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('allow', 'Дозволити'), ('check', 'Перевіряти'), ('drop', 'Заборонити')], default='drop', max_length=20)),
                ('priority', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('recipient', models.ManyToManyField(related_name='recipient_rules', to='analyzer.email')),
                ('sender', models.ManyToManyField(related_name='sender_rules', to='analyzer.email')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
